### ISSUE TITLE
storybook-react-context: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ldeveber** [tyom/storybook-addons#20] opened 2021-08-02 20:20 UTC
From https://tyom.github.io/storybook-addons/react/?path=/story/storybook-react-context--change-context-on-mount&fixtures=.0

```
RangeError: Maximum call stack size exceeded
    at sortObject (https://tyom.github.io/storybook-addons/react/vendors~main.17a6b5f5.iframe.bundle.js:2:417487)
    at https://tyom.github.io/storybook-addons/react/vendors~main.17a6b5f5.iframe.bundle.js:2:417758
    at Array.reduce (<anonymous>)
    at sortObject (https://tyom.github.io/storybook-addons/react/vendors~main.17a6b5f5.iframe.bundle.js:2:417665)
    at https://tyom.github.io/storybook-addons/react/vendors~main.17a6b5f5.iframe.bundle.js:2:417758
    at Array.reduce (<anonymous>)
    at sortObject (https://tyom.github.io/storybook-addons/react/vendors~main.17a6b5f5.iframe.bundle.js:2:417665)
    at https://tyom.github.io/storybook-addons/react/vendors~main.17a6b5f5.iframe.bundle.js:2:417758
    at Array.reduce (<anonymous>)
    at sortObject (https://tyom.github.io/storybook-addons/react/vendors~main.17a6b5f5.iframe.bundle.js:2:417665)
```

<img width="1397" alt="Screen Shot 2021-08-02 at 4 18 57 PM" src="https://user-images.githubusercontent.com/4457752/127918776-c2c354f9-f9f7-41c7-b426-afa0e0af792f.png">

**Comment by tyom** [comment] 2021-08-04 19:47
Hi @ldeveber. Thanks for reporting the issue. I've been working on updating the packages to work with the latest Storybook version and should have it resolved soon.

Thanks for your patience.

**Comment by tyom** [comment] 2021-08-05 00:43
I've published new versions of the packages. The issue should be fixed now.

**Comment by tyom** [comment] 2021-08-09 16:32
@ldeveber can you confirm if the issue is fixed for you?

**Comment by tyom** [comment] 2021-08-21 21:39
Closing due to inactivity.

**Closed by tyom** 2021-08-21 21:39 UTC
